[tool.setuptools]
py-modules = []

[tool.black]
line-length = 79
skip-string-normalization = true

[tool.isort]
line_length = 79
profile = 'black'
sections = ['FUTURE', 'STDLIB', 'THIRDPARTY', 'LIBS', 'FIRSTPARTY', 'LOCALFOLDER']
